services:
  agentgateway:
    container_name: agentgateway
    restart: unless-stopped
    image: cr.agentgateway.dev/agentgateway:v1.1.0
    ports:
      - "3000:3000"
      - "127.0.0.1:15000:15000"
    volumes:
      - ./config.yaml:/config.yaml
    environment:
      - ADMIN_ADDR=0.0.0.0:15000
    command: ["-f", "/config.yaml"]
    depends_on:
      - mcp-everything

  mcp-everything:
    container_name: mcp-everything
    image: node:22-alpine
    command: npx -y @modelcontextprotocol/server-everything sse
    ports:
      - "3001:3001"
