#Base image der indeholder python image og uv version
FROM afsluttende-projekt-base:latest

WORKDIR /app

COPY requirements.txt .
RUN uv pip install --system --no-build -r requirements.txt

COPY credentials-api/credentials_api.py .
COPY credentials-api/templates/ ./templates/

RUN mkdir -p /data

CMD ["python", "-m", "uvicorn", "credentials_api:app", "--host", "0.0.0.0", "--port", "8001"]